server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://username:password@localhost:27017/admin}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

