server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://username:password@localhost:27017/admin}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

