server:
  port: 8082

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://username:password@localhost:27017/admin}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}

