server:
  port: 8082

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://username:password@mongo_db:27017/admin}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://discovery-server:8761/eureka}
resilience4j:
  circuitbreaker:
    instances:
      companyBreaker:
        register-health-indicator: true
        registerHealthIndicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state:
          seconds: 10
        failure-rate-threshold: 50
        allow-health-indicator-to-fail: true
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
  retry:
    configs:
      companyBreaker:
        max-attempts: 5
  ratelimiter:
    configs:
      companyBreaker:
        timeout-duration: 0
        limit-refresh-period:
          seconds: 5
        limit-for-period: 1

